#!/bin/bash

set -e

echo "===== Updating system ====="
sudo apt update -y

echo "===== Installing Java 17 ====="
sudo apt install -y openjdk-17-jdk

java -version

echo "===== Adding Jenkins repository ====="
curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null

echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
https://pkg.jenkins.io/debian-stable binary/" | sudo tee \
/etc/apt/sources.list.d/jenkins.list > /dev/null

echo "===== Installing Jenkins ====="
sudo apt update -y
sudo apt install -y jenkins

echo "===== Starting Jenkins ====="
sudo systemctl enable jenkins
sudo systemctl start jenkins
sudo systemctl status jenkins --no-pager

echo "===== Installing Maven ====="
sudo apt install -y maven

mvn -version

echo "===== Jenkins & Maven installation completed successfully ====="

